# Generated by Django 2.2.4 on 2019-08-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('patronymic', models.CharField(max_length=25)),
                ('mob_tel_num', models.CharField(blank=True, max_length=11, null=True)),
                ('em', models.EmailField(blank=True, max_length=254, null=True)),
                ('subdivision', models.CharField(db_index=True, max_length=25)),
            ],
        ),
    ]
