# Generated by Django 2.2.4 on 2019-08-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='surname',
            new_name='surnsurnameame',
        ),
    ]
