# Generated by Django 2.2.4 on 2019-08-28 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telweb', '0002_auto_20190827_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='InTel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(db_index=True, max_length=4, verbose_name='Внутренний номер')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
                'ordering': ['tel'],
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['subdivision'], 'verbose_name': 'Абонент', 'verbose_name_plural': 'Абоненты'},
        ),
        migrations.AlterField(
            model_name='person',
            name='em',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mob_tel_num',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='patronymic',
            field=models.CharField(max_length=25, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='person',
            name='subdivision',
            field=models.CharField(db_index=True, max_length=25, verbose_name='Номер подраздиления'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surnsurnameame',
            field=models.CharField(max_length=25, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='person',
            name='extension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='telweb.InTel', verbose_name='Внутренний номер'),
        ),
    ]
