# Generated by Django 2.2.4 on 2019-08-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telweb', '0003_auto_20190828_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mob_tel_num',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Мобильный телефон'),
        ),
    ]
