# Generated by Django 2.2.4 on 2019-08-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telweb', '0005_auto_20190828_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='telweb.Cabinet', verbose_name='Номер кабинета'),
        ),
    ]
