# Generated by Django 2.2.4 on 2019-08-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telweb', '0006_person_ir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='ir',
        ),
    ]
