# Generated by Django 2.2.4 on 2019-08-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telweb', '0007_remove_person_ir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intel',
            name='tel',
            field=models.CharField(db_index=True, max_length=4, unique=True, verbose_name='Внутренний номер'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='filial',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Филиал'),
        ),
    ]
