# Generated by Django 2.2.4 on 2019-08-30 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telweb', '0008_auto_20190829_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', related_query_name='entry', to='telweb.Organization', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='intel',
            name='in_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', related_query_name='entry', to='telweb.Cabinet', verbose_name='Номер кабинета'),
        ),
        migrations.AlterField(
            model_name='person',
            name='extension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', related_query_name='entry', to='telweb.InTel', verbose_name='Внутренний номер'),
        ),
    ]
